[tool.ruff]
line-length = 200
exclude = [
    "typings",
    "venv"
]
extend-include = ["*.ipynb"]

[tool.ruff.lint.per-file-ignores]
"**/{notebooks}/*" = ["E402", "E401"]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
